# Generated by Django 3.0.3 on 2020-03-03 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Switchapi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50)),
                ('switch0', models.CharField(default=None, max_length=50)),
                ('switch1', models.CharField(default=None, max_length=50)),
                ('switch2', models.CharField(default=None, max_length=50)),
                ('switch3', models.CharField(default=None, max_length=50)),
                ('phone_no', models.IntegerField()),
            ],
        ),
    ]
