# Generated by Django 3.0.3 on 2020-03-03 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartswitchapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switchapi',
            name='switch0',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='switchapi',
            name='switch1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='switchapi',
            name='switch2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='switchapi',
            name='switch3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
